### ISSUE TITLE
Saving PDBx file instead of PDB 

### ISSUE THREAD

**Issue by MuhammadIIsmail** [openmm/openmm-setup#25]
I am preparing a system with > 100,000 atoms which the PDB file can not translate for the CONECT section of some residues (e.g. small molecule). 

How can I save PDBx file instead?

**Comment by peastman** [comment]
Are you referring to the processed files that get written while cleaning up your input files?  It should use whatever type of file you provide.  If you give it a PDBx file as input, it will write out files in the same format.

**Comment by MuhammadIIsmail** [comment]
Yes, I refer to that. 
When I tried to use PDBx (.cif) file it gave "internal server error". 
Is there any way to handle this?

**Comment by peastman** [comment]
That doesn't sound right!

Take a look in the terminal window you launched it from.  Error messages should have been written there, including a stack trace.  Can you post the output?

Also make sure you're using the latest version (1.2).

**Comment by MuhammadIIsmail** [comment]
This is the error message that appears:
_________________________________
127.0.0.1 - - [16/Mar/2021 19:12:22] "GET /selectFiles?type=pdb HTTP/1.1" 200 -
[2021-03-16 19:12:42,005] ERROR in app: Exception on /configureFiles [POST]
Traceback (most recent call last):
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/openmmsetup/openmmsetup.py", line 102, in configureFiles
    fixer = PDBFixer(pdbxfile=StringIO(file.read().decode()))
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 254, in __init__
    self._initializeFromPDBx(pdbxfile)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 309, in _initializeFromPDBx
    entityIdCol = sequenceData.getAttributeIndex('entity_id')
AttributeError: 'NoneType' object has no attribute 'getAttributeIndex'
127.0.0.1 - - [16/Mar/2021 19:12:42] "POST /configureFiles HTTP/1.1" 500 -


Also, I made sure that I am using v 1.2

openmm-setup              1.2                pyhd3deb0d_0    conda-forge

**Comment by peastman** [comment]
Your version of PDBFixer is out of date.  That line number doesn't match the current version.  Try upgrading it and see if that fixes the error.

**Comment by MuhammadIIsmail** [comment]
I updated PDBFixer and made sure that PDBFixer, flask and OpenMM are up-to-date:

flask                     1.1.2              pyh9f0ad1d_0    conda-forge
openmm                    7.5.0            py37h724217f_6    conda-forge
pdbfixer                  1.6                        py_1    omnia

However, the same error appears:

127.0.0.1 - - [17/Mar/2021 05:38:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 05:38:08] "GET /static/Icon.svg HTTP/1.1" 200 -
127.0.0.1 - - [17/Mar/2021 05:38:12] "GET /selectFiles?type=pdb HTTP/1.1" 200 -
[2021-03-17 05:42:40,393] ERROR in app: Exception on /configureFiles [POST]
Traceback (most recent call last):
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/openmmsetup/openmmsetup.py", line 102, in configureFiles
    fixer = PDBFixer(pdbxfile=StringIO(file.read().decode()))
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 254, in __init__
    self._initializeFromPDBx(pdbxfile)
  File "/home/ismail/anaconda3/lib/python3.7/site-packages/pdbfixer/pdbfixer.py", line 309, in _initializeFromPDBx
    entityIdCol = sequenceData.getAttributeIndex('entity_id')
AttributeError: 'NoneType' object has no attribute 'getAttributeIndex'
127.0.0.1 - - [17/Mar/2021 05:42:40] "POST /configureFiles HTTP/1.1" 500 -

**Comment by peastman** [comment]
>  pdbfixer 1.6 py_1 omnia

The current version is 1.7, not 1.6.  Install it with

```
conda install -c conda-forge pdbfixer
```

**Comment by MuhammadIIsmail** [comment]
Thank you, sir. It now works with PDBx files.

**Comment by peastman** [comment]
Great!  Glad that's working.  I'll close this, since I think everything has been answered.
