### ISSUE TITLE
Issues with running simulation

### ISSUE THREAD

**Issue by debanjansen48** [openmm/openmm-setup#39]
it returns following issue PFA scripts

Building system...
Traceback (most recent call last):
  File "/home/debanjan/Desktop/openmm/run_openmm_simulation.py", line 44, in <module>
    system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debanjan/miniconda3/envs/openmm/lib/python3.12/site-packages/openmm/app/forcefield.py", line 1247, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debanjan/miniconda3/envs/openmm/lib/python3.12/site-packages/openmm/app/forcefield.py", line 1462, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 224 (ASN).  The set of atoms is similar to NASN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
[run_openmm_simulation.txt](https://github.com/openmm/openmm-setup/files/15153110/run_openmm_simulation.txt)

**Comment by peastman** [comment]
Just after you select your input file, it asks whether you need to clean it up.  Did you say yes?  Adding missing atoms is one of the problems it can fix.
